workspace:
  base: /srv/app
  path: src/github.com/go-gitea/go-sdk

pipeline:
  testing:
    image: webhippie/golang:latest
    pull: true
    commands:
      - make clean
      - make vet
      - make lint
      - make test
      - make build

  coverage:
    image: plugins/coverage

  gitter:
    image: plugins/gitter
